spring:
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小


# 自定义文件保存路径
gorit:
  file:
    root:
      path: F:\\sfz\\